
package com.nt.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.nt.res.bindings.BookResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Book", targetNamespace = "http://service.nt.com/")
@XmlSeeAlso({
    com.nt.res.bindings.ObjectFactory.class,
    com.nt.service.ObjectFactory.class
})
public interface Book {


    /**
     * 
     * @param bookId
     * @return
     *     returns com.nt.res.bindings.BookResType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBook", targetNamespace = "http://service.nt.com/", className = "com.nt.service.SearchBook")
    @ResponseWrapper(localName = "searchBookResponse", targetNamespace = "http://service.nt.com/", className = "com.nt.service.SearchBookResponse")
    @Action(input = "http://service.nt.com/Book/searchBookRequest", output = "http://service.nt.com/Book/searchBookResponse")
    public BookResType searchBook(
        @WebParam(name = "bookId", targetNamespace = "")
        int bookId);

}
