//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.02 at 11:44:45 AM IST 
//


package bank.sbi.account;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bank.sbi.account package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bankaccount_QNAME = new QName("http://bank/sbi/account", "bankaccount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bank.sbi.account
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BankaccountType }
     * 
     */
    public BankaccountType createBankaccountType() {
        return new BankaccountType();
    }

    /**
     * Create an instance of {@link CurrentAccountType }
     * 
     */
    public CurrentAccountType createCurrentAccountType() {
        return new CurrentAccountType();
    }

    /**
     * Create an instance of {@link SavingAccountType }
     * 
     */
    public SavingAccountType createSavingAccountType() {
        return new SavingAccountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankaccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bank/sbi/account", name = "bankaccount")
    public JAXBElement<BankaccountType> createBankaccount(BankaccountType value) {
        return new JAXBElement<BankaccountType>(_Bankaccount_QNAME, BankaccountType.class, null, value);
    }

}
