//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 11:55:32 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/nt/res/weather", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nt.res.weather;
