
package com.nt.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.nt.req.bindings.JourneyInfoType;
import com.nt.req.bindings.PassengerInfoType;
import com.nt.res.bindings.TicketType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ticket", targetNamespace = "http://service.nt.com/")
@XmlSeeAlso({
    com.nt.req.bindings.ObjectFactory.class,
    com.nt.res.bindings.ObjectFactory.class,
    com.nt.service.ObjectFactory.class
})
public interface Ticket {


    /**
     * 
     * @param journeyInfo
     * @param passengerInfo
     * @return
     *     returns com.nt.res.bindings.TicketType
     */
    @WebMethod
    @WebResult(name = "request", targetNamespace = "")
    @RequestWrapper(localName = "bookTicket", targetNamespace = "http://service.nt.com/", className = "com.nt.service.BookTicket")
    @ResponseWrapper(localName = "bookTicketResponse", targetNamespace = "http://service.nt.com/", className = "com.nt.service.BookTicketResponse")
    @Action(input = "http://service.nt.com/Ticket/bookTicketRequest", output = "http://service.nt.com/Ticket/bookTicketResponse")
    public TicketType bookTicket(
        @WebParam(name = "PassengerInfo", targetNamespace = "")
        PassengerInfoType passengerInfo,
        @WebParam(name = "JourneyInfo", targetNamespace = "")
        JourneyInfoType journeyInfo);

}
