//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 11:55:27 AM IST 
//


package com.nt.req.weather;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WeatherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WeatherReport" type="{http://com/nt/req/weather}WeatherReportType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherType", propOrder = {
    "weatherReport"
})
@XmlRootElement(name="WeatherRequestType")
public class WeatherType {

    @XmlElement(name = "WeatherReport", required = true)
    protected WeatherReportType weatherReport;

    /**
     * Gets the value of the weatherReport property.
     * 
     * @return
     *     possible object is
     *     {@link WeatherReportType }
     *     
     */
    public WeatherReportType getWeatherReport() {
        return weatherReport;
    }

    /**
     * Sets the value of the weatherReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeatherReportType }
     *     
     */
    public void setWeatherReport(WeatherReportType value) {
        this.weatherReport = value;
    }

}
